"use client";

import { Dumbbell, Brain, Apple, Wallet, ShieldAlert, Users, type LucideIcon } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ExplainabilityTooltip } from "@/components/shared/explainability-tooltip";
import type { ProgramRecommendation, RecommendationResult } from "@/lib/subsystem-a";

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  fitness: Dumbbell,
  mental_health: Brain,
  nutrition: Apple,
  financial_wellness: Wallet,
};

const CATEGORY_LABEL: Record<string, string> = {
  fitness: "Fitness",
  mental_health: "Mental Health",
  nutrition: "Nutrition",
  financial_wellness: "Financial Wellness",
};

const STATUS_BADGE: Record<
  string,
  { className: string; label: string }
> = {
  available: {
    className:
      "border-[var(--risk-low)]/40 bg-[color-mix(in_oklch,var(--risk-low)_16%,transparent)] text-[#1B4332]",
    label: "Available",
  },
  near_capacity: {
    className:
      "border-[var(--risk-medium)]/40 bg-[color-mix(in_oklch,var(--risk-medium)_18%,transparent)] text-[#7A4A12]",
    label: "Near Capacity",
  },
  full: {
    className:
      "border-[var(--risk-high)]/40 bg-[color-mix(in_oklch,var(--risk-high)_16%,transparent)] text-[#7A1620]",
    label: "Full",
  },
};

function RecommendationCard({ rec }: { rec: ProgramRecommendation }) {
  const CategoryIcon = CATEGORY_ICONS[rec.program.category] ?? Dumbbell;
  const statusBadge = STATUS_BADGE[rec.status];

  return (
    <Card className="transition-shadow hover:shadow-[var(--shadow-card-hover)]">
      <CardHeader className="pb-2">
        <div className="flex items-start justify-between gap-2">
          <CardTitle className="text-base leading-tight">{rec.program.name}</CardTitle>
          <span
            className={`shrink-0 inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-medium ${statusBadge.className}`}
          >
            {statusBadge.label}
          </span>
        </div>
        <div className="flex items-center gap-2 text-xs text-muted-foreground mt-0.5">
          <Badge variant="secondary" className="gap-1">
            <CategoryIcon className="size-3" />
            {CATEGORY_LABEL[rec.program.category]}
          </Badge>
          <span>{rec.program.provider}</span>
        </div>
      </CardHeader>
      <CardContent className="space-y-2">
        <p className="text-sm text-foreground/85 leading-relaxed">{rec.explanation}</p>
        <div className="flex items-center justify-between">
          <ExplainabilityTooltip
            reason={`Matched based on your employee profile and "${rec.program.category.replace("_", " ")}" category affinity. This recommendation is generated by VitalPulse's matching engine and reviewed for relevance.`}
          />
          <span className="text-[10px] text-muted-foreground flex items-center gap-1">
            <Users className="size-3" />
            {rec.program.enrolledCount}/{rec.program.capacity} enrolled
          </span>
        </div>
      </CardContent>
    </Card>
  );
}

export function RecommendedPrograms({ result }: { result: RecommendationResult }) {
  // Suppression message (conflict rule or dept burnout-flagged)
  if (result.suppressed) {
    return (
      <Card className="bg-[color-mix(in_oklch,var(--risk-medium)_8%,transparent)] border-[var(--risk-medium)]/30">
        <CardContent className="pt-4 flex items-start gap-2.5">
          <ShieldAlert className="size-4 mt-0.5 shrink-0 text-[#7A4A12]" />
          <p className="text-sm text-[#7A4A12]">{result.suppressed}</p>
        </CardContent>
      </Card>
    );
  }

  // No recommendations (opted-out is already handled upstream, but just in case)
  if (result.recommendations.length === 0) {
    return (
      <p className="text-sm text-muted-foreground">
        No program recommendations available right now — check back soon.
      </p>
    );
  }

  return (
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      {result.recommendations.map((rec) => (
        <RecommendationCard key={rec.program.id} rec={rec} />
      ))}
    </div>
  );
}
